### ISSUE TITLE
Hamamatsu camera serial numbers are not matched properly

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/navigate#411]
The cameras appear to be assigned to the microscope by the order in which they are listed in the hardware section, not just the serial number. E.g., if I specify `302352` for `Mesoscale` Hamamatsu serial number and `501002` for `Nanoscale` serial number but pass them as 

```
hardware:
  daq:
    type: NI
  camera:
    -
      type: HamamatsuOrca
      serial_number: 302352
    -
      type: HamamatsuOrca
      serial_number: 501002
```

then `302352` will get assigned to `Nanoscale` and vice versa. However, if I flip the order to 

```
hardware:
  daq:
    type: NI
  camera:
    -
      type: HamamatsuOrca
      serial_number: 501002
    -
      type: HamamatsuOrca
      serial_number: 302352
```

they are assigned correctly.

P.S. I think @AdvancedImagingUTSW called this one a while ago.
